#!/usr/bin/env sh
CMDZ="$1"
PROCNM="kiagateway"
PROCNMCMD="/opt/kiagateway/bin/kiagateway /opt/kiagateway/etc/config.toml"

skillo() {
  pkill $PROCNM || pkill -9 $PROCNM
}

if [ "$CMDZ" == "start" ]; then  
  pgrep $PROCNM || $PROCNMCMD &
fi
if [ "$CMDZ" == "restart" ]; then
  skillo && $PROCNMCM &
fi
if [ "$CMDZ" == "stop" ]; then
  skillo 
fi
