#!/usr/bin/env sh
CMDZ="$1"
PROCNM="kiamagpie"
skillo() {
  pkill $PROCNM || pkill -9 $PROCNM
}

if [ "$CMDZ" == "start" ]; then
  pgrep $PROCNM || cd /opt/kiamagpie/ && /usr/local/bin/kiamagpie > /var/log/magpie.log 2>&1 &
fi
if [ "$CMDZ" == "restart" ]; then
  skillo && cd /opt/kiamagpie/ && /usr/local/bin/kiamagpie > /var/log/magpie.log 2>&1 &
fi
if [ "$CMDZ" == "stop" ]; then
  skillo
fi
