#!/usr/bin/env sh
CMDZ="$1"
PROCNM="morpho-server-template"

skillo() {
  pkill $PROCNM && pgrep $PROCNM && pkill -9 $PROCNM
}

if [ "$CMDZ" == "start" ]; then  
  pgrep $PROCNM || su - crab -c 'cd /home/crab/template && MORPHOP=changeme && /home/crab/template/$PROCNM' &
fi
if [ "$CMDZ" == "restart" ]; then
  skillo && su - crab -c 'cd /home/crab/template && MORPHOP=changeme && /home/crab/template/$PROCNM' &
fi
if [ "$CMDZ" == "stop" ]; then
  skillo
fi
