#!/usr/bin/env sh
CMDZ="$1"
PROCNM="kiamagpie"
skillo() {
  pkill $PROCNM || pgrep $PROCNM && pkill -9 $PROCNM
}

if [ "$CMDZ" == "start" ]; then
  pgrep $PROCNM || cd /opt/kiamagpie/ && /usr/local/bin/kiamagpie > /dev/null 2>&1 &
  # JSON event output mode, use this instead:
  #pgrep $PROCNM || cd /opt/kiamagpie/ && /usr/local/bin/kiamagpie > /var/log/magpie.log 2>&1 &
fi
if [ "$CMDZ" == "restart" ]; then
  skillo;
  pgrep $PROCNM || cd /opt/kiamagpie/ && /usr/local/bin/kiamagpie > /dev/null 2>&1 &
  # JSON event output mode, use this instead:
  #pgrep $PROCNM || cd /opt/kiamagpie/ && /usr/local/bin/kiamagpie > /var/log/magpie.log 2>&1 &
fi
if [ "$CMDZ" == "stop" ]; then
  skillo
fi
