#!/usr/bin/env bash

chainsplit() {
  file="$1"
  awk '
    BEGIN { n=0; split_after=0 }
    {
      if (n == 0) out="cert.pem"
      else out="cert" n ".pem"

      print > out
    }
    /-----END CERTIFICATE-----/ {
      n++
    }
  ' < "$file"
}

TEMPLATErenew() {
  cp /etc/letsencrypt/live/www.example.com/privkey.pem /opt/local/TEMPLATE/key.pem &&
  chainsplit /etc/letsencrypt/live/www.example.com/fullchain.pem &&
  dz3=$(ls cert3.pem || echo NZ)
  if [ "$dz3" != "NZ" ]; then
    cat cert.pem cert1.pem cert2.pem > /opt/local/TEMPLATE/cert.pem
  else
    cat cert.pem cert1.pem > /opt/local/TEMPLATE/cert.pem
  fi
  chmod 600 /opt/local/TEMPLATE/key.pem
}

TEMPLATErenew
rm cert.pem cert1.pem cert2.pem 2>/dev/null
