#!/usr/bin/env bash

chainsplit() {
  file="$1"
  awk '
    /-----END CERTIFICATE-----/ {
        print >> ("cert" n ".pem")
        close("cert" n ".pem")
        n++
        next
    }
    {
        print >> ("cert" n ".pem")
    }
  ' "$file"
}

TEMPLATErenew() {
  cp /etc/letsencrypt/live/www.example.com/privkey.pem /opt/local/TEMPLATE/key.pem &&
  chainsplit /etc/letsencrypt/live/www.example.com/fullchain.pem &&
  cat cert.pem cert1.pem > /opt/local/TEMPLATE/cert.pem
  chmod 600 /opt/local/TEMPLATE/key.pem
}

TEMPLATErenew
